import './globals.css'
import { Inter } from 'next/font/google'
import Footer from './components/footer';
import Navbar from './components/navbar';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`flex flex-col min-h-screen ${inter.className}`}>
       <Navbar /> 
        <main className="flex-grow">
          {children}
        </main>
       <Footer /> 
      </body>
    </html>
  )
}
